### ISSUE TITLE
Only Half of the Tab is Shown

### ISSUE THREAD

**Issue by viking2** [piroor/tst-active-tab-in-collapsed-tree#5]
This is my Tree before collapse, with "Whitmer.." active:
https://i.gyazo.com/4ba04edb3dd1a53a36153358b0107c1e.png

This is my Tree after collapse:
https://i.gyazo.com/b73efc347b70d52ba336ae51aa12777b.png
As you can see, only half of the Tab is shown.

The problem arise because I modified the Tab Height and Font like this:
```
tab-item {
  --tab-size: 25px !important;
  height: var(--tab-size);
  font-size: 15px;
}
```
1. How do I change the code to make it compatible with your Add-on?

2. Also, I would like to have an option to highlight the last active Tab in each tree when it is **not** collapsed. Maybe that can be done directly in TST..?

TIA!

**Comment by piroor** [comment]
You can change the font size in the fake tab element with a style declaration like:

```css
::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp title) {
  font-size: 10px;
}
```

**Comment by piroor** [comment]
> Also, I would like to have an option to highlight the last active Tab in each tree when it is not collapsed. 

It can be done with:

```css
  tab-item:not(.subtree-collapsed) ::part(extra-contents-by-tst-active-tab-in-collapsed-tree_piro_sakura_ne_jp container) {
  visibility: visible !important;
}
```
